/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_network_dialog (void)
{
  GtkWidget *network_dialog;
  GtkWidget *network_vbox;
  GtkWidget *network_table;
  GtkWidget *connection_label;
  GtkWidget *dhcp_toggle;
  GtkWidget *connection_list;
  GtkWidget *address_label;
  GtkWidget *address_entry;
  GtkWidget *subnet_label;
  GtkWidget *subnet_entry;
  GtkWidget *renew_button;
  GtkWidget *router_label;
  GtkWidget *dns_label;
  GtkWidget *router_entry;
  GtkWidget *dns_scrolled;
  GtkWidget *dns_text;
  GtkWidget *empty_label;
  GtkWidget *enable_toggle;
  GtkWidget *warning_label;
  GtkWidget *warning_icon;
  GtkWidget *nm_hbox;
  GtkWidget *nm_toggle;
  GtkWidget *nm_button;
  GtkWidget *network_actions;
  GtkWidget *network_revert_button;
  GtkWidget *network_apply_button;
  GtkWidget *network_close_button;

  network_dialog = gtk_dialog_new ();
  gtk_widget_set_name (network_dialog, "network_dialog");
  gtk_window_set_title (GTK_WINDOW (network_dialog), _("Network Settings"));
  gtk_window_set_type_hint (GTK_WINDOW (network_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  network_vbox = GTK_DIALOG (network_dialog)->vbox;
  gtk_widget_set_name (network_vbox, "network_vbox");
  gtk_widget_show (network_vbox);

  network_table = gtk_table_new (9, 4, FALSE);
  gtk_widget_set_name (network_table, "network_table");
  gtk_widget_show (network_table);
  gtk_box_pack_start (GTK_BOX (network_vbox), network_table, FALSE, FALSE, 5);
  gtk_table_set_row_spacings (GTK_TABLE (network_table), 5);
  gtk_table_set_col_spacings (GTK_TABLE (network_table), 5);

  connection_label = gtk_label_new (_("Connection:"));
  gtk_widget_set_name (connection_label, "connection_label");
  gtk_widget_show (connection_label);
  gtk_table_attach (GTK_TABLE (network_table), connection_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (connection_label), 1, 0.5);

  dhcp_toggle = gtk_check_button_new_with_mnemonic (_("Configure automatically"));
  gtk_widget_set_name (dhcp_toggle, "dhcp_toggle");
  gtk_widget_show (dhcp_toggle);
  gtk_table_attach (GTK_TABLE (network_table), dhcp_toggle, 1, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  connection_list = gtk_combo_box_new_text ();
  gtk_widget_set_name (connection_list, "connection_list");
  gtk_widget_show (connection_list);
  gtk_table_attach (GTK_TABLE (network_table), connection_list, 1, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (connection_list), _("Ethernet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (connection_list), _("Ethernet 1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (connection_list), _("Wireless"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (connection_list), _("Wireless 1"));

  address_label = gtk_label_new (_("Address:"));
  gtk_widget_set_name (address_label, "address_label");
  gtk_widget_show (address_label);
  gtk_table_attach (GTK_TABLE (network_table), address_label, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (address_label), 1, 0.5);

  address_entry = gtk_entry_new ();
  gtk_widget_set_name (address_entry, "address_entry");
  gtk_widget_show (address_entry);
  gtk_table_attach (GTK_TABLE (network_table), address_entry, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (address_entry), 9679);

  subnet_label = gtk_label_new (_("Subnet Mask:"));
  gtk_widget_set_name (subnet_label, "subnet_label");
  gtk_widget_show (subnet_label);
  gtk_table_attach (GTK_TABLE (network_table), subnet_label, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (subnet_label), 1, 0.5);

  subnet_entry = gtk_entry_new ();
  gtk_widget_set_name (subnet_entry, "subnet_entry");
  gtk_widget_show (subnet_entry);
  gtk_table_attach (GTK_TABLE (network_table), subnet_entry, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (subnet_entry), 9679);

  renew_button = gtk_button_new_with_mnemonic (_("Refresh Connection"));
  gtk_widget_set_name (renew_button, "renew_button");
  gtk_widget_show (renew_button);
  gtk_table_attach (GTK_TABLE (network_table), renew_button, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 0);

  router_label = gtk_label_new (_("Router:"));
  gtk_widget_set_name (router_label, "router_label");
  gtk_widget_show (router_label);
  gtk_table_attach (GTK_TABLE (network_table), router_label, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (router_label), 1, 0.5);

  dns_label = gtk_label_new (_("DNS Servers:"));
  gtk_widget_set_name (dns_label, "dns_label");
  gtk_widget_show (dns_label);
  gtk_table_attach (GTK_TABLE (network_table), dns_label, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (dns_label), 1, 0.5);

  router_entry = gtk_entry_new ();
  gtk_widget_set_name (router_entry, "router_entry");
  gtk_widget_show (router_entry);
  gtk_table_attach (GTK_TABLE (network_table), router_entry, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (router_entry), 9679);

  dns_scrolled = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (dns_scrolled, "dns_scrolled");
  gtk_widget_show (dns_scrolled);
  gtk_table_attach (GTK_TABLE (network_table), dns_scrolled, 1, 4, 6, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (dns_scrolled), GTK_POLICY_NEVER, GTK_POLICY_NEVER);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (dns_scrolled), GTK_SHADOW_IN);

  dns_text = gtk_text_view_new ();
  gtk_widget_set_name (dns_text, "dns_text");
  gtk_widget_show (dns_text);
  gtk_container_add (GTK_CONTAINER (dns_scrolled), dns_text);

  empty_label = gtk_label_new (_("\n"));
  gtk_widget_set_name (empty_label, "empty_label");
  gtk_widget_show (empty_label);
  gtk_table_attach (GTK_TABLE (network_table), empty_label, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (empty_label), 0, 0.5);

  enable_toggle = gtk_check_button_new_with_mnemonic (_("Enable connection"));
  gtk_widget_set_name (enable_toggle, "enable_toggle");
  gtk_widget_show (enable_toggle);
  gtk_table_attach (GTK_TABLE (network_table), enable_toggle, 1, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  warning_label = gtk_label_new ("");
  gtk_widget_set_name (warning_label, "warning_label");
  gtk_table_attach (GTK_TABLE (network_table), warning_label, 1, 4, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (warning_label), 0, 0.5);

  warning_icon = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (warning_icon, "warning_icon");
  gtk_table_attach (GTK_TABLE (network_table), warning_icon, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (warning_icon), 1, 0.5);

  nm_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (nm_hbox, "nm_hbox");
  gtk_widget_show (nm_hbox);
  gtk_table_attach (GTK_TABLE (network_table), nm_hbox, 1, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  nm_toggle = gtk_check_button_new_with_mnemonic (_("Use NetworkManager to control active connections"));
  gtk_widget_set_name (nm_toggle, "nm_toggle");
  gtk_widget_show (nm_toggle);
  gtk_box_pack_start (GTK_BOX (nm_hbox), nm_toggle, TRUE, TRUE, 0);

  nm_button = gtk_button_new_with_mnemonic (_("Configure Network Manager"));
  gtk_widget_set_name (nm_button, "nm_button");
  gtk_widget_show (nm_button);
  gtk_box_pack_start (GTK_BOX (nm_hbox), nm_button, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (nm_button, FALSE);

  network_actions = GTK_DIALOG (network_dialog)->action_area;
  gtk_widget_set_name (network_actions, "network_actions");
  gtk_widget_show (network_actions);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (network_actions), GTK_BUTTONBOX_END);

  network_revert_button = gtk_button_new_from_stock ("gtk-revert-to-saved");
  gtk_widget_set_name (network_revert_button, "network_revert_button");
  gtk_widget_show (network_revert_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (network_dialog), network_revert_button, GTK_RESPONSE_REJECT);
  GTK_WIDGET_SET_FLAGS (network_revert_button, GTK_CAN_DEFAULT);

  network_apply_button = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (network_apply_button, "network_apply_button");
  gtk_widget_show (network_apply_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (network_dialog), network_apply_button, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (network_apply_button, GTK_CAN_DEFAULT);

  network_close_button = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (network_close_button, "network_close_button");
  gtk_widget_show (network_close_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (network_dialog), network_close_button, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (network_close_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) dhcp_toggle, "toggled",
                    G_CALLBACK (on_dhcp_toggle_toggled),
                    NULL);
  g_signal_connect ((gpointer) connection_list, "changed",
                    G_CALLBACK (on_connection_list_changed),
                    NULL);
  g_signal_connect ((gpointer) address_entry, "changed",
                    G_CALLBACK (on_address_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) subnet_entry, "changed",
                    G_CALLBACK (on_subnet_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) renew_button, "clicked",
                    G_CALLBACK (on_renew_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) router_entry, "changed",
                    G_CALLBACK (on_router_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) enable_toggle, "toggled",
                    G_CALLBACK (on_enable_toggle_toggled),
                    NULL);
  g_signal_connect ((gpointer) nm_toggle, "toggled",
                    G_CALLBACK (on_nm_toggle_toggled),
                    NULL);
  g_signal_connect ((gpointer) nm_button, "clicked",
                    G_CALLBACK (on_nm_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) network_revert_button, "clicked",
                    G_CALLBACK (on_revert_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) network_apply_button, "clicked",
                    G_CALLBACK (on_apply_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) network_close_button, "clicked",
                    G_CALLBACK (on_close_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (network_dialog, network_dialog, "network_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (network_dialog, network_vbox, "network_vbox");
  GLADE_HOOKUP_OBJECT (network_dialog, network_table, "network_table");
  GLADE_HOOKUP_OBJECT (network_dialog, connection_label, "connection_label");
  GLADE_HOOKUP_OBJECT (network_dialog, dhcp_toggle, "dhcp_toggle");
  GLADE_HOOKUP_OBJECT (network_dialog, connection_list, "connection_list");
  GLADE_HOOKUP_OBJECT (network_dialog, address_label, "address_label");
  GLADE_HOOKUP_OBJECT (network_dialog, address_entry, "address_entry");
  GLADE_HOOKUP_OBJECT (network_dialog, subnet_label, "subnet_label");
  GLADE_HOOKUP_OBJECT (network_dialog, subnet_entry, "subnet_entry");
  GLADE_HOOKUP_OBJECT (network_dialog, renew_button, "renew_button");
  GLADE_HOOKUP_OBJECT (network_dialog, router_label, "router_label");
  GLADE_HOOKUP_OBJECT (network_dialog, dns_label, "dns_label");
  GLADE_HOOKUP_OBJECT (network_dialog, router_entry, "router_entry");
  GLADE_HOOKUP_OBJECT (network_dialog, dns_scrolled, "dns_scrolled");
  GLADE_HOOKUP_OBJECT (network_dialog, dns_text, "dns_text");
  GLADE_HOOKUP_OBJECT (network_dialog, empty_label, "empty_label");
  GLADE_HOOKUP_OBJECT (network_dialog, enable_toggle, "enable_toggle");
  GLADE_HOOKUP_OBJECT (network_dialog, warning_label, "warning_label");
  GLADE_HOOKUP_OBJECT (network_dialog, warning_icon, "warning_icon");
  GLADE_HOOKUP_OBJECT (network_dialog, nm_hbox, "nm_hbox");
  GLADE_HOOKUP_OBJECT (network_dialog, nm_toggle, "nm_toggle");
  GLADE_HOOKUP_OBJECT (network_dialog, nm_button, "nm_button");
  GLADE_HOOKUP_OBJECT_NO_REF (network_dialog, network_actions, "network_actions");
  GLADE_HOOKUP_OBJECT (network_dialog, network_revert_button, "network_revert_button");
  GLADE_HOOKUP_OBJECT (network_dialog, network_apply_button, "network_apply_button");
  GLADE_HOOKUP_OBJECT (network_dialog, network_close_button, "network_close_button");

  return network_dialog;
}

GtkWidget*
create_changes_dialog (void)
{
  GtkWidget *changes_dialog;
  GtkWidget *changes_vbox;
  GtkWidget *changes_hbox;
  GtkWidget *changes_image;
  GtkWidget *changes_label;
  GtkWidget *changes_actions;
  GtkWidget *changes_dont_button;
  GtkWidget *changes_cancel_button;
  GtkWidget *changes_apply_button;

  changes_dialog = gtk_dialog_new ();
  gtk_widget_set_name (changes_dialog, "changes_dialog");
  gtk_window_set_title (GTK_WINDOW (changes_dialog), _("Network Settings"));
  gtk_window_set_type_hint (GTK_WINDOW (changes_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  changes_vbox = GTK_DIALOG (changes_dialog)->vbox;
  gtk_widget_set_name (changes_vbox, "changes_vbox");
  gtk_widget_show (changes_vbox);

  changes_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (changes_hbox, "changes_hbox");
  gtk_widget_show (changes_hbox);
  gtk_box_pack_start (GTK_BOX (changes_vbox), changes_hbox, TRUE, TRUE, 20);

  changes_image = gtk_image_new_from_icon_name ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_set_name (changes_image, "changes_image");
  gtk_widget_show (changes_image);
  gtk_box_pack_start (GTK_BOX (changes_hbox), changes_image, FALSE, FALSE, 20);

  changes_label = gtk_label_new (_("Apply changed settings?"));
  gtk_widget_set_name (changes_label, "changes_label");
  gtk_widget_show (changes_label);
  gtk_box_pack_start (GTK_BOX (changes_hbox), changes_label, TRUE, TRUE, 20);
  gtk_misc_set_padding (GTK_MISC (changes_label), 4, 0);

  changes_actions = GTK_DIALOG (changes_dialog)->action_area;
  gtk_widget_set_name (changes_actions, "changes_actions");
  gtk_widget_show (changes_actions);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (changes_actions), GTK_BUTTONBOX_END);

  changes_dont_button = gtk_button_new_with_mnemonic (_("Don't Apply"));
  gtk_widget_set_name (changes_dont_button, "changes_dont_button");
  gtk_widget_show (changes_dont_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (changes_dialog), changes_dont_button, GTK_RESPONSE_REJECT);
  GTK_WIDGET_SET_FLAGS (changes_dont_button, GTK_CAN_DEFAULT);

  changes_cancel_button = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (changes_cancel_button, "changes_cancel_button");
  gtk_widget_show (changes_cancel_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (changes_dialog), changes_cancel_button, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (changes_cancel_button, GTK_CAN_DEFAULT);

  changes_apply_button = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (changes_apply_button, "changes_apply_button");
  gtk_widget_show (changes_apply_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (changes_dialog), changes_apply_button, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (changes_apply_button, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (changes_dialog, changes_dialog, "changes_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (changes_dialog, changes_vbox, "changes_vbox");
  GLADE_HOOKUP_OBJECT (changes_dialog, changes_hbox, "changes_hbox");
  GLADE_HOOKUP_OBJECT (changes_dialog, changes_image, "changes_image");
  GLADE_HOOKUP_OBJECT (changes_dialog, changes_label, "changes_label");
  GLADE_HOOKUP_OBJECT_NO_REF (changes_dialog, changes_actions, "changes_actions");
  GLADE_HOOKUP_OBJECT (changes_dialog, changes_dont_button, "changes_dont_button");
  GLADE_HOOKUP_OBJECT (changes_dialog, changes_cancel_button, "changes_cancel_button");
  GLADE_HOOKUP_OBJECT (changes_dialog, changes_apply_button, "changes_apply_button");

  return changes_dialog;
}

GtkWidget*
create_applying_dialog (void)
{
  GtkWidget *applying_dialog;
  GtkWidget *applying_hbox;
  GtkWidget *applying_image;
  GtkWidget *applying_label;

  applying_dialog = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (applying_dialog, "applying_dialog");
  gtk_window_set_title (GTK_WINDOW (applying_dialog), _("Network Settings"));
  gtk_window_set_position (GTK_WINDOW (applying_dialog), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_modal (GTK_WINDOW (applying_dialog), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (applying_dialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (applying_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  applying_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (applying_hbox, "applying_hbox");
  gtk_widget_show (applying_hbox);
  gtk_container_add (GTK_CONTAINER (applying_dialog), applying_hbox);
  gtk_container_set_border_width (GTK_CONTAINER (applying_hbox), 20);

  applying_image = gtk_image_new_from_icon_name ("gtk-dialog-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_set_name (applying_image, "applying_image");
  gtk_widget_show (applying_image);
  gtk_box_pack_start (GTK_BOX (applying_hbox), applying_image, FALSE, FALSE, 20);

  applying_label = gtk_label_new (_("Applying changes..."));
  gtk_widget_set_name (applying_label, "applying_label");
  gtk_widget_show (applying_label);
  gtk_box_pack_start (GTK_BOX (applying_hbox), applying_label, TRUE, TRUE, 20);
  gtk_misc_set_padding (GTK_MISC (applying_label), 4, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (applying_dialog, applying_dialog, "applying_dialog");
  GLADE_HOOKUP_OBJECT (applying_dialog, applying_hbox, "applying_hbox");
  GLADE_HOOKUP_OBJECT (applying_dialog, applying_image, "applying_image");
  GLADE_HOOKUP_OBJECT (applying_dialog, applying_label, "applying_label");

  return applying_dialog;
}

GtkWidget*
create_error_dialog (void)
{
  GtkWidget *error_dialog;
  GtkWidget *error_vbox;
  GtkWidget *error_table;
  GtkWidget *error_label;
  GtkWidget *error_scrolled;
  GtkWidget *error_text;
  GtkWidget *error_image;
  GtkWidget *error_actions;
  GtkWidget *error_ok_button;

  error_dialog = gtk_dialog_new ();
  gtk_widget_set_name (error_dialog, "error_dialog");
  gtk_window_set_title (GTK_WINDOW (error_dialog), _("Network Settings"));
  gtk_window_set_type_hint (GTK_WINDOW (error_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  error_vbox = GTK_DIALOG (error_dialog)->vbox;
  gtk_widget_set_name (error_vbox, "error_vbox");
  gtk_widget_show (error_vbox);

  error_table = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (error_table, "error_table");
  gtk_widget_show (error_table);
  gtk_box_pack_start (GTK_BOX (error_vbox), error_table, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (error_table), 20);
  gtk_table_set_row_spacings (GTK_TABLE (error_table), 20);
  gtk_table_set_col_spacings (GTK_TABLE (error_table), 20);

  error_label = gtk_label_new (_("<b>There was an error doing something:</b>"));
  gtk_widget_set_name (error_label, "error_label");
  gtk_widget_show (error_label);
  gtk_table_attach (GTK_TABLE (error_table), error_label, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (error_label, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (error_label), TRUE);
  gtk_label_set_justify (GTK_LABEL (error_label), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (error_label), TRUE);
  gtk_label_set_selectable (GTK_LABEL (error_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (error_label), 0, 0.5);

  error_scrolled = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (error_scrolled, "error_scrolled");
  gtk_widget_show (error_scrolled);
  gtk_table_attach (GTK_TABLE (error_table), error_scrolled, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (error_scrolled), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (error_scrolled), GTK_SHADOW_IN);

  error_text = gtk_text_view_new ();
  gtk_widget_set_name (error_text, "error_text");
  gtk_widget_show (error_text);
  gtk_container_add (GTK_CONTAINER (error_scrolled), error_text);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (error_text), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (error_text), GTK_WRAP_WORD);

  error_image = gtk_image_new_from_icon_name ("gtk-dialog-error", GTK_ICON_SIZE_DIALOG);
  gtk_widget_set_name (error_image, "error_image");
  gtk_widget_show (error_image);
  gtk_table_attach (GTK_TABLE (error_table), error_image, 0, 1, 0, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (error_image), 0.5, 0);

  error_actions = GTK_DIALOG (error_dialog)->action_area;
  gtk_widget_set_name (error_actions, "error_actions");
  gtk_widget_show (error_actions);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (error_actions), GTK_BUTTONBOX_END);

  error_ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (error_ok_button, "error_ok_button");
  gtk_widget_show (error_ok_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (error_dialog), error_ok_button, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (error_ok_button, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (error_dialog, error_dialog, "error_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (error_dialog, error_vbox, "error_vbox");
  GLADE_HOOKUP_OBJECT (error_dialog, error_table, "error_table");
  GLADE_HOOKUP_OBJECT (error_dialog, error_label, "error_label");
  GLADE_HOOKUP_OBJECT (error_dialog, error_scrolled, "error_scrolled");
  GLADE_HOOKUP_OBJECT (error_dialog, error_text, "error_text");
  GLADE_HOOKUP_OBJECT (error_dialog, error_image, "error_image");
  GLADE_HOOKUP_OBJECT_NO_REF (error_dialog, error_actions, "error_actions");
  GLADE_HOOKUP_OBJECT (error_dialog, error_ok_button, "error_ok_button");

  return error_dialog;
}

