/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_network_dialog (void);
GtkWidget* create_changes_dialog (void);
GtkWidget* create_applying_dialog (void);
GtkWidget* create_error_dialog (void);
