/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include "lobster.h"

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h"

int
main (int argc, char *argv[])
{
  GError *error = NULL;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  if (!lobster_system_load (&error)) {
      lobster_show_error (_("<b>Could not load network configuration:</b>"), error);
      return 1;
  }

  lobster.dialog = create_network_dialog ();

  /* glade can't do this automatically... */
  g_signal_connect (BUFFER ("dns_text"), "changed", G_CALLBACK (on_dns_text_changed), NULL);

  lobster_system_display ();
  
  if (!g_file_test ("/usr/bin/nm-editor", G_FILE_TEST_IS_EXECUTABLE)) {
      gtk_widget_hide (WIDGET ("nm_button"));
  }

  gtk_widget_hide (WIDGET ("renew_button"));
  gtk_widget_show (lobster.dialog);

  gtk_main ();

  return 0;
}

